### ISSUE TITLE
Copy an instance anywhere

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#330] opened 2016-06-21 22:33 UTC
Add feature to copy any (accessible) instance to another (accessible) location. 

Provenance of copied instance should be captured in its (meta)metadata.

Ideally, to this in a way that an IRI can be handed out to make this an action (like create is an IRI action now). Default can be to current directory if writable, else user's directory.

**Comment by martinjoconnor** [comment] 2016-06-21 22:42
We have a copy/move task in #296.

**Comment by graybeal** [comment] 2016-06-21 23:31
well sure, now that you added ‘copy’ in a comment!

the comment I added on the other task is worth saving I think

john

On Jun 21, 2016, at 3:42 PM, martinjoconnor <notifications@github.com<mailto:notifications@github.com>> wrote:


We have a copy/move task in #296<https://github.com/metadatacenter/cedar-template-editor/issues/296>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/metadatacenter/cedar-template-editor/issues/330#issuecomment-227594374>, or mute the thread<https://github.com/notifications/unsubscribe/ABNU0ObTiQr8fRpvQ_pB_sT5rhxIpq2wks5qOGjygaJpZM4I7PW8>.

========================
John Graybeal
Technical Program Manager
Center for Expanded Data Annotation and Retrieval /+/ NCBO BioPortal
Stanford Center for Biomedical Informatics Research
650-736-1632
skype: graybealski

**Comment by martinjoconnor** [comment] 2016-09-19 22:19
Duplicate of #511

**Closed** 2016-09-19 22:19 UTC
Labels: feature
