### ISSUE TITLE
Add "shared with me" to move and copy dialogs

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#740] opened 2018-03-02 22:39 UTC
Currently limited to a fixed number. Should scroll. Not clear if this will require server side pagination.

Related to:

https://github.com/metadatacenter/cedar-template-editor/issues/632

**Comment by michelleif** [comment] 2018-03-05 22:23
What lead to finding this issue was trying to copy or move something to a folder that someone else shared with me. Which meant I had to know **where** in that person's folder structure the shared folder lived, and then navigate to that person's user folder and then find the shared folder. So what would be much easier is if when you do "copy" or "move" you could click a "shared with me" to see folders that are shared with you and choose to "copy" or "move" into one of those. Would have to show only folders that you have write access to.

**Comment by willrett** [comment] 2018-04-17 19:32
duplicate of #696

**Closed** 2018-04-17 19:33 UTC
Labels: LD4P, Sharing, enhancement, in progress
