### ISSUE TITLE
Controlled term auto-complete broken in Medata Editor

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#600] opened 2017-04-05 05:30 UTC
Use branch rooted in 'Injury type' in NCBI ontology to reproduce.

**Comment by marcosmro** [comment] 2017-04-05 05:54
This is a duplicate of https://github.com/metadatacenter/cedar-template-editor/issues/598, which I closed last week. The fix is still in the development branch. It hasn't been applied to staging or production yet.

**Closed by marcosmro** 2017-04-05 05:54 UTC
Labels: bug, Release 1.1 - LD4P, UX
