### ISSUE TITLE
Cannot change the element label when the multiple option is true

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#730] opened 2018-01-23 01:00 UTC
**Steps to reproduce**:
1. Create an element
2. Create a template using that element
3. Set the multiple options = true
4. Change the field label for that element

The label will change back to the original element name

**Comment by willrett** [comment] 2018-01-25 23:37
duplicate of #610

**Closed by willrett** 2018-01-25 23:37 UTC
Labels: analyze, bug
