### ISSUE TITLE
Autocomplete shows the same term repeated multiple times

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#553] opened 2016-12-09 18:09 UTC
Sometimes, the BioPortal search endpoint returns the same class repeated multiple times. The cause is that in some cases an ontology contains several copies of the same class, either because the ontology developer defined several copies of them, in different places of the hierarchy, or because they come from different ontologies that are imported from the main one. CEDAR should only show one occurrence of the term to avoid confusion (see screenshot).

![screen shot 2016-12-09 at 9 52 10 am](https://cloud.githubusercontent.com/assets/7634440/21059542/b1429e66-bdf7-11e6-91b4-ac57c285d2bf.png)

**Comment by martinjoconnor** [comment] 2017-08-09 16:36
@marcosmro , is this effectively a duplicate of #555?

**Comment by marcosmro** [comment] 2017-08-09 16:41
No, it's not a duplicate. This issue refers to the behavior of autocomplete when filling out a template using the Metadata Editor. #555 is about class search in the ontology modal.

**Comment by mdorf** [comment] 2017-09-27 19:12
Marcos will provide a BioPortal REST call that's responsible for these results.

**Comment by mdorf** [comment] 2017-09-27 19:39
Per discussion with @marcosmro and Jennifer, one possible solution for this would be to add an optional parameter to BioPortal search that would eliminate duplicate results on the SAME term from the SAME ontology. This parameter must remain optional because the general "autocomplete" BioPortal search may want to show duplicates in cases where the location of the term in the ontology tree is important to the user.

Time estimate: 7 days

**Comment by marcosmro** [comment] 2017-09-27 21:03
Here is an example of BioPortal REST call that returns multiple "asthma" results:
http://data.bioontology.org/search?q=asthma&also_search_provisional=true&ontology_types=ONTOLOGY&suggest=true&ontology=DOID&subtree_root_id=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_4&max_depth=0&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true

**Comment by marcosmro** [comment] 2017-09-27 21:53
By taking a look at the results of the previous call, it seems that the subtree search endpoint is returning "asthma" classes from multiple ontologies (DOID, BAO, NIFSTD, etc.), when it should only return classes from DOID.

**Comment by graybeal** [comment] 2017-09-29 17:23
This is a bug, and Misha is working on it.

**Comment by marcosmro** [comment] 2017-10-12 21:47
It's done and waiting for release.

**Closed** 2017-12-01 18:08 UTC
Labels: BioPortal
