### ISSUE TITLE
'Create template' doesn't respond in the page listing all the Template Elements. 

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#194] opened 2016-04-28 14:17 UTC
I have checked the list of issues and I don't think this bug has been reported. Apologies if it is already listed.

Steps
1. login
2. choose 'Design Template' option
3. select 'See All' in the 'Template Elements' section
4. press 'Create New Template' 
and nothing happens.

**Comment by martinjoconnor** [comment] 2016-04-28 15:14
Duplicate of cedar-project#34.

We have decided not to fix this because this screen will be replaced in the next few days.

**Comment by agbeltran** [comment] 2016-04-28 15:16
OK, thanks - didn't know that there was another set of issues :)

**Closed** 2016-04-28 15:15 UTC

**Comment by martinjoconnor** [comment] 2016-04-28 15:19
Waffle (https://waffle.io/metadatacenter/cedar-project) has them all in one place - though finding issues can be hard. 

Feel free to report anything you find, even if you think it could already be there. I can easily deal with duplicates.
