### ISSUE TITLE
cannot delete fields when editing an Element

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-template-editor#684] opened 2017-07-13 23:15 UTC
Create an Element.
Adda text field.
Try to delete the field using the X in upper right-hand corner. The X doesn't do anything.
Tried to delete a field from a Template and it worked fine.
Tried on Mac on both Safari and Firefox. Tried on other Templates and other fields, same problem.

**Comment by marcosmro** [comment] 2017-07-13 23:20
Duplicate of https://github.com/metadatacenter/cedar-project/issues/513. The fix will be released to production tomorrow.

**Closed by marcosmro** 2017-07-13 23:20 UTC
