### ISSUE TITLE
Search & Browse - Display Resources

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#132] opened 2016-03-23 21:24 UTC
https://basecamp.com/1771528/projects/9018044/messages/55893534

**Comment by acarlton** [comment] 2016-03-31 00:21
@egyedia I have updated my branch locally with the most recent changes from develop. I am still getting a JavaScript error when calling Cedar.getHome() :

```TypeError: Cannot read property 'homePath' of null```

It appears the cedarUserProfile property is null. I am trying this code by including my new service in the dashboard controller and loading the page. I've been looking, but not entirely sure how you have this user initialization code loaded with the app... Do you have any ideas?

**Comment by egyedia** [comment] 2016-03-31 02:05
Hi,
could you please try the following:
0) Update all repos, do a full build.
1) Log out from the application
2) Drop all the documents from the "users" collection from your MongoDb.
3) Log in to the application. A new profile should be created in the "users" collection. Please check if the document has the homePath set.
4) Merge the develop branch to your local branch - if you did not do that already. That code should use the homePath from the proper place.

If doing these steps won't fix the problem, let me know.

Attila

**Comment by acarlton** [comment] 2016-03-31 19:27
@egyedia I performed all the above steps you mentioned and am still getting the error. Any other ideas?

**Comment by acarlton** [comment] 2016-03-31 19:40
@egyedia I think I may have some more information from testing that might be helpful. Based on the simple debugging test code I've committed to the feature/search-browse branch, I'm noticing that if you load the app at:

https://cedar.metadatacenter.orgx 

and then CLICK on the design template button, I don't see the JavaScript error. However, when I RELOAD that page, I see the error. Perhaps the user object is getting set on a specific controller or page you are assuming is happening earlier in the user flow? When I load the page via URL, without navigating through that process, it's not available...

**Comment by egyedia** [comment] 2016-03-31 20:04
@acarlton My system is currently in a non-runnable state, but I will check this ASAP and let you know.

**Comment by egyedia** [comment] 2016-03-31 20:48
@acarlton 
Hi Aaron,
I just pushed a file to the editor, logging the user home.
I guess the issue is because of timing. in the "run.js" the UserData is read from a REST endpoint in the following block:

    UserService.init(function () {
      UserDataService.readUserDetails();
    });

When the rest info is returned, that is the point that the user-specific information is available to the application.
I hope this helps.
I guess UserDataService.readUserDetails could take also a callback function as argument, and that would be the point where things should start their operation.
Let me know if you think this can work in this way, or you see/prefer other ways around.

Attila

**Comment by egyedia** [comment] 2016-04-01 23:43
@acarlton 

Hi Aaron,
I just pushed a modification, which loads the user info before the angular app is started.
I added some sample code into run.js to log some data into the console (line 453):

    console.log("Cedar service providing user data at this point:");
    console.log(Cedar.getUserId());
    console.log(Cedar.getScreenName());
    console.log(Cedar.getHome());

It is done in a non-angular way, with jQuery. Since a small angular app is already available at that point, maybe later I will refactor it to align better with angular.
But it does the job reliably based on my tests.

I hope this helps. Let us know what you think.

Attila

**Comment by acarlton** [comment] 2016-04-02 00:05
@egyedia I am also trying to hardcode the path parameter for this API call to keep making progress with the resource API integration, but I'm receiving a 404 error using this url:
```https://resource.metadatacenter.orgx/folders?path=/Users/394c230b-ed59-4959-95b7-e7195fcb5aa6&resource_types=field,element,template,instance```
I'm using httpBuilderService.get(url) and passing it into the authorizedBackendService. Do you think a similar initialization issue could be affecting this issue when getting the token? Wondering if you have any other ideas, my request headers are:

```GET /folders?path=/Users/394c230b-ed59-4959-95b7-e7195fcb5aa6&resource_types=field,element,template,instance HTTP/1.1
Host: resource.metadatacenter.orgx
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: https://cedar.metadatacenter.orgx
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJkZjM5NWJjMS02OWVkLTQ0YTktOTZhMi1lNjBjMzU1MGU4NTIiLCJleHAiOjE0NTk1NTU2MTYsIm5iZiI6MCwiaWF0IjoxNDU5NTU1MzE2LCJpc3MiOiJodHRwczovL2F1dGgubWV0YWRhdGFjZW50ZXIub3JneC9hdXRoL3JlYWxtcy9DRURBUiIsImF1ZCI6ImNlZGFyLWFuZ3VsYXItYXBwIiwic3ViIjoiMzk0YzIzMGItZWQ1OS00OTU5LTk1YjctZTcxOTVmY2I1YWE2IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2VkYXItYW5ndWxhci1hcHAiLCJub25jZSI6IjhiOTI5MDRhLTZhNzMtNGY4Mi1hMWJlLTY1ZTU2YzMyMGIwZiIsInNlc3Npb25fc3RhdGUiOiIwZGM4YjhmMy01MGEwLTQ1N2EtYTZhMS0yZDQ0Nzg5MDM3MWIiLCJjbGllbnRfc2Vzc2lvbiI6IjExZmY2MjRmLWEzYzYtNGRlNS05NjYyLWJkMDBkYjc3YTMyYSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2NlZGFyLm1ldGFkYXRhY2VudGVyLm9yZ3giLCJodHRwOi8vY2VkYXIubWV0YWRhdGFjZW50ZXIub3JneCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiY2FwYWJpbGl0eV9pbnN0YW5jZV9kZWxldGUiLCJjYXBhYmlsaXR5X3RlbXBsYXRlX2NyZWF0ZSIsImNhcGFiaWxpdHlfZWxlbWVudF91cGRhdGUiLCJjYXBhYmlsaXR5X2luc3RhbmNlX3VwZGF0ZSIsImNhcGFiaWxpdHlfaW5zdGFuY2VfcmVhZCIsInJvbGVfaW5zdGFuY2VfZWRpdG9yIiwiY2FwYWJpbGl0eV9lbGVtZW50X2RlbGV0ZSIsImNhcGFiaWxpdHlfaW5zdGFuY2VfY3JlYXRlIiwiY2FwYWJpbGl0eV90ZW1wbGF0ZV9hbnkiLCJjYXBhYmlsaXR5X3RlbXBsYXRlX2RlbGV0ZSIsImNhcGFiaWxpdHlfdGVtcGxhdGVfdXBkYXRlIiwicm9sZV9hbGwiLCJjYXBhYmlsaXR5X2luc3RhbmNlX2FueSIsImNhcGFiaWxpdHlfZWxlbWVudF9yZWFkIiwiY2FwYWJpbGl0eV9lbGVtZW50X2NyZWF0ZSIsImNhcGFiaWxpdHlfZWxlbWVudF9hbnkiLCJjYXBhYmlsaXR5X3RlbXBsYXRlX3JlYWQiLCJyb2xlX2VsZW1lbnRfZWRpdG9yIiwicm9sZV90ZW1wbGF0ZV9lZGl0b3IiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IkFhcm9uIENhcmx0b24iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYXJvbkBvcmRpbmFyeWV4cGVydHMuY29tIiwiZ2l2ZW5fbmFtZSI6IkFhcm9uIiwiZmFtaWx5X25hbWUiOiJDYXJsdG9uIiwiZW1haWwiOiJhYXJvbkBvcmRpbmFyeWV4cGVydHMuY29tIn0.RbAwe4bdLPZ73l3hc4fi8zr0uChrnF5LjCTUJMVHkODLMFakLrlAHPuJgdmTw9LTyW7azmXz5dACSA__R5iNcJWnMCylT1phmudF2h9ZRSRPbDK95AguB5PhWdqoTJjp_naUsJB8jRkTqrnv2pv5EhYqyNaRayMDDtNPt1TGJNo8AYF4YQK0VV0KvW5jaLEG3QW2ntZPIt8H34XNev0tcgxS8HjiqBkn067yw06ozSGHhpx5xFn5ecyDf3SM-Ynp6HxCLAVPj69jBhCrQ30IxKBOQRlE6oorf68Qf7qn_KGjH8RM7aKY-N8ts3v4FEqgpQVhbXkhGb0S3W6cq0XwYg
Referer: https://cedar.metadatacenter.orgx/dashboard/as-creator
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

**Comment by egyedia** [comment] 2016-04-04 16:09
@acarlton Hi Aaron,

I responded to this via email over the weekend, but it seems that the email just disappeared.
So here is my original answer:
--------------
Hi Aaron.

The endpoint is not returning data for now. The Call seems to be ok.
I will provide dummy data in the response ön Monday.
Until then, maybe you could load a static json file, just to test the other functions.

Attila

**Closed** 2016-04-27 04:37 UTC
Labels: feature, UX
