### ISSUE TITLE
deleting workspace item doesn't refresh display

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#493] opened 2016-08-10 22:42 UTC
select a folder, element, or template in the workspace and click delete in the toolbar.  the confirmation popup is displayed, but the item remains.  refreshing the browser shows that the item has been deleted.

**Comment by martinjoconnor** [comment] 2016-08-10 23:35
Duplicate of #351

**Closed** 2016-08-10 23:35 UTC
