### ISSUE TITLE
Multiple instance text field with value constraint defined fails

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#213] opened 2016-05-11 00:20 UTC
The drop down is not populated correctly if the field is multiple cardinality.

**Comment by graybeal** [comment] 2016-05-11 23:16
(And if a set of legal values has been defined.)

**Comment by graybeal** [comment] 2016-05-11 23:17
See also #211

**Comment by martinjoconnor** [comment] 2016-08-09 21:49
Duplicate of #175.

**Closed** 2016-08-09 21:50 UTC
Labels: bug, Release 0.8, UX
