### ISSUE TITLE
Templates need version field

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#84] opened 2016-02-19 17:39 UTC
The templates lack a means of indicating provenance except as free text in the description. This should include a version indicator.  ImmPort templates are versioned for each software release.

**Comment by martinjoconnor** [comment] 2016-02-19 19:01
Related to metadatacenter/cedar-template-server#6 on the server side.

**Comment by martinjoconnor** [comment] 2017-04-27 01:48
Duplicate of https://github.com/metadatacenter/cedar-model-validation-library/issues/16

**Closed by martinjoconnor** 2017-04-27 01:48 UTC
Labels: duplicate
