### ISSUE TITLE
Issue with saving template

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#681] opened 2017-07-13 16:30 UTC
After creating a template and saving it, when trying to go back (clicking the arrow at the top left of the screen), I get a dialog box asking "Are you sure? Your recent changes will be lost" (even if it was just saved).

**Comment by martinjoconnor** [comment] 2017-07-14 00:48
Duplicate of #508

**Closed** 2017-07-14 00:50 UTC
Labels: duplicate

**Comment by agbeltran** [comment] 2017-07-20 11:35
Hi @martinjoconnor  - #508 is about the sharing templates functionality. Maybe you meant it was a duplicate of another issue?

**Comment by martinjoconnor** [comment] 2017-07-21 14:21
You are right. Wrong 508: https://github.com/metadatacenter/cedar-project/issues/508

**Comment by agbeltran** [comment] 2017-07-21 14:27
ok, thanks! the cedar-project repository has the issues that apply for all tools, I guess?

**Comment by martinjoconnor** [comment] 2017-07-21 15:16
Yup.  We are not religious about  it, but we try to put tasks in relevant repos (cedar-metadata-editor for front end issues, for example). When in doubt, cedar-project works.
